### ISSUE TITLE
Unable to find in maven repository

### ISSUE THREAD

**Issue by vaithu** [belomx/vaadin-paper-input-place#2] opened 2021-04-07 02:57 UTC
Hi,

I was trying to find this in mvn repository but unable to locate it. Could you please check?

**Comment by belomx** [comment] 2021-04-07 12:53
Hi,

Sorry I forgot to add the link to the vaadin directory. Here is the link:
[https://vaadin.com/directory/component/paper-input-place-component](url)

Regards, I hope you like the project :)

**Comment by vaithu** [comment] 2021-04-07 13:25
Sorry. I still do not see it there. I search here https://mvnrepository.com/
and add it to the Pom.xml.

I still get, not found error for

<dependency>
    <groupId>org.vaadin.addon</groupId>
    <artifactId>vaadin-paper-input-place</artifactId>
    <version>1.0.1</version>
</dependency>


Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by belomx** [comment] 2021-04-07 13:32
Hi,

Did you added the repository of vaadin directory?

`<repository>
   <id>vaadin-addons</id>
   <url>https://maven.vaadin.com/vaadin-addons</url>
</repository>`

Regards

**Comment by vaithu** [comment] 2021-04-07 13:35
yes. I already have this.


<repository>
    <id>Vaadin Directory</id>
    <url>https://maven.vaadin.com/vaadin-addons</url>
    <snapshots>
        <enabled>false</enabled>
    </snapshots>
</repository>

Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by belomx** [comment] 2021-04-07 14:00
Hi,

In the pom.xml, is the id correct? Because the part that you have pasted in the comment is wrong.
`<id>Vaadin Directory</id>`

Regards

**Comment by vaithu** [comment] 2021-04-07 14:08
It looks to me that's valid because it is from the starter page and I see
the URL is the same and the id can be anything understandable.

It is more of not available for maven. That's what I'm thinking because I'm
able to get other plug-ins without issues.

Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by belomx** [comment] 2021-04-07 17:42
Hi,

Could run a clean, the install again and send the error?

Regards

**Comment by vaithu** [comment] 2021-04-07 19:20
Yes. That fixed the problem. But now,the component is erroring out and this
is the message from the developer tool.

<input id="nativeInput" inputmode="text" placeholder="Oops! Something went
wrong." class="pac-target-input gm-err-autocomplete" autocomplete="off"
disabled="" style="background-image: url(&quot;
https://maps.gstatic.com/mapfiles/api-3/images/icon_error.png&quot;);">

I'm using v14 and that might be the reason for the error?


Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by vaithu** [comment] 2021-04-07 19:21
and this is the code I use

PaperInputPlace place = new
PaperInputPlace("API-KEY");
place.setCountry("IN");
place.setLanguage("en");
place.addValueChangeEventListener(valueChangeEvent -> {
    Notification.show(valueChangeEvent.getValue());
});

Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by vaithu** [comment] 2021-04-07 19:24
and this is how it looks 

![image](https://user-images.githubusercontent.com/35440074/113922463-4f492300-97b5-11eb-8347-a9b1ea316d2b.png)

**Comment by belomx** [comment] 2021-04-07 19:27
Hi,

I can't state the problem is directly related to vaadin 14, but I have only tested with vaadin 17. Is a option for you to move the project to vaadin 17?

Regards,
Danilo

**Comment by vaithu** [comment] 2021-04-08 17:05
I tested with vaadin 19 and got the same problem.

**Comment by belomx** [comment] 2021-04-08 17:09
Hi,

Is possible to publish the problem somehow in a public repository, so I can debug it?

Regards,

**Comment by vaithu** [comment] 2021-04-08 17:16
Thanks for your prompt reply always.

All I did was,


   1. Downloaded a starter project from vaadin.com/start
   2. Added Paper place input dependency into the pom XML
   3.

   <dependency>
       <groupId>org.vaadin.addon</groupId>
       <artifactId>vaadin-paper-input-place</artifactId>
       <version>1.0.1</version>
   </dependency>

   4.

   Modified HelloWord like below

   5.

   public HelloWorldView() {


       PaperInputPlace place = new PaperInputPlace("API-KEY");
       place.setCountry("IN");
       place.setLanguage("en");
       place.addValueChangeEventListener(valueChangeEvent -> {
           Notification.show(valueChangeEvent.getValue());
       });

       add(place);

   }

   6.

   Run the application and see the component

   7.

   Component errors out saying "Something unknown occurred". Is this
because, my API-KEY is not activated by Google or should I do some
other steps other than generating the key from Google Maps?



Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by belomx** [comment] 2021-04-08 17:37
Hi, 

To confirm if the problem is related to API-KEY, go to development tab of your browser, and check the console after you get the "rendering error". Because the API-Key is mandatory, you need to create a project in google cloud and enable it.
Here is tutorial to get the key [https://developers.google.com/maps/documentation/javascript/places-autocomplete](url)

Regards,

**Comment by vaithu** [comment] 2021-04-08 18:11
Yes. There is a problem with the API-KEY.

 *Google Maps JavaScript API error: ApiNotActivatedMapError*
https://developers.google.com/maps/documentation/javascript/error-messages#api-not-activated-map-

I've already enabled Places MAP API but still it doesn't work.


Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by belomx** [comment] 2021-04-08 18:16
Hi,

It takes several minutes to be available. Check the console in the browser if the error disappeared.

Regards

**Comment by vaithu** [comment] 2021-04-09 19:24
It is working now. Thanks for helping me in fixing this.

One last question, is there a way to get the directions from
Latitude/Longitude? I need the values like NORTH, SOUTH etc.


Regards

S Kadhir

IIB Remote Support|Training|Consultation

+1(612) 305 8684

www.vaithu.com

**Comment by belomx** [comment] 2021-04-09 19:26
Hi,

The Lat/Log is returned, test with the example below:
inputPlace.addChangePlacejsonCompleteEventListener(e -> {
            e.getSource().getPlaceResponse().ifPresent(response -> {
                selectedValueLabel.setText(response.toString());
            });
        });
        
Regards,

**Comment by belomx** [comment] 2021-04-09 19:26
Closing the issue as the original problem was solved.

**Closed as completed by belomx** 2021-04-09 19:26 UTC
